Description:
  RDS for external monitoring

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: Common parameters
        Parameters:
          - ServiceName
          - StageName
      -
        Label:
          default: Database parameters
        Parameters:
          - EngineVersion
          - DBInstanceClass
          - AllocatedStorage
        
Parameters:
  ServiceName:
    Description: ServiceName name
    Type: String
    Default: "external-monitoring"
  StageName:
    Description: Stage name
    Type: String
    Default: "loc"
    AllowedValues:
      - loc
      - dev
      - stg
      - prod
  EngineVersion:
    Type: String
    AllowedValues:
      - "8.0.32"
      - "8.0.33"
      - "8.0.34"
      - "8.0.35"
      - "8.0.36"
    Default: "8.0.36"

  DBInstanceClass:
    Description: The compute and memory capacity of the RDS instance
    Type: String
    Default: "db.t3.micro"
    AllowedValues:
      - "db.t3.micro"
      - "db.t3.small"

  AllocatedStorage:
    Type: Number
    Description: The size of the database (Gb)
    Default: 20
    MinValue: 5
    MaxValue: 3072
    ConstraintDescription: must be between 5 and 3072 Gb.

Resources:

  #----------------------------------------
  # RDS DB Secret
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
  #----------------------------------------
  RDSDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${ServiceName}-${StageName}-mysql-secret"
      Description: This is a Secrets Manager secret for a Redshift cluster
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"'@/\\"
      Tags:
        - Key: Name
          Value: !Sub "${ServiceName}-${StageName}-mysql-secret"
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StageName
          Value: !Ref StageName

  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${ServiceName}-${StageName}-subnet-group-mysql"
      DBSubnetGroupDescription: "DB Subnet Group for Aurora Serverless"
      SubnetIds: 
        - Fn::ImportValue: !Sub "${ServiceName}-${StageName}-subnet-db-1"
        - Fn::ImportValue: !Sub "${ServiceName}-${StageName}-subnet-db-2"
      Tags: 
        - Key: Name
          Value: !Sub "${ServiceName}-${StageName}-subnet-group-mysql"
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StageName
          Value: !Ref StageName

  #----------------------------------------
  # RDS DB Instance
  #----------------------------------------
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${ServiceName}-${StageName}-mysql-instance"
      Engine: mysql
      EngineVersion: !Ref EngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Sub "{{resolve:secretsmanager:${RDSDBSecret}::username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${RDSDBSecret}::password}}"
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - Fn::ImportValue: !Sub "${ServiceName}-${StageName}-sg-db"
      AllocatedStorage: !Ref AllocatedStorage
      Tags:
        - Key: Name
          Value: !Sub "${ServiceName}-${StageName}-mysql-instance"
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StageName
          Value: !Ref StageName

  DBSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref RDSDBSecret
      TargetId: !Ref RDSDBInstance
      TargetType: AWS::RDS::DBCluster

  #----------------------------------------
  # IAM Role for RDS Proxy
  #----------------------------------------
  DBProxyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
               - rds.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Ref DBProxyPolicy
      Tags:
        - Key: Name
          Value: !Sub "${ServiceName}-${StageName}-mysql-secret-role"      
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StageName
          Value: !Ref StageName
    DependsOn: DBProxyPolicy

  DBProxyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows reading secrets from AWS Secrets Manager."
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Ref DBSecretAttachment
    DependsOn: DBSecretAttachment

  #----------------------------------------
  # RDS DB Proxy
  #----------------------------------------
  DBProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      DBProxyName: !Sub "${ServiceName}-${StageName}-mysql-proxy"
      EngineFamily: MYSQL
      RoleArn: !GetAtt DBProxyRole.Arn
      Auth:
        - AuthScheme: SECRETS
          IAMAuth: DISABLED
          SecretArn: !Ref DBSecretAttachment
      VpcSubnetIds: 
        - Fn::ImportValue: !Sub "${ServiceName}-${StageName}-subnet-private-1"
        - Fn::ImportValue: !Sub "${ServiceName}-${StageName}-subnet-private-2"
      VpcSecurityGroupIds: 
        - Fn::ImportValue: !Sub ${ServiceName}-${StageName}-sg-db-proxy
      Tags:
      - Key: Name
        Value: !Sub "${ServiceName}-${StageName}-mysql-proxy"
      - Key: ServiceName
        Value: !Ref ServiceName
      - Key: StageName
        Value: !Ref StageName
    DependsOn:
      - DBProxyRole
      - DBSecretAttachment

  #----------------------------------------
  # RDS DB Proxy Target Group
  #----------------------------------------
  DBProxyTargetGroup: 
   Type: AWS::RDS::DBProxyTargetGroup
   Properties:
      DBProxyName: !Ref DBProxy
      TargetGroupName: default
      DBInstanceIdentifiers:
        - !Ref RDSDBInstance
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: 100
        MaxIdleConnectionsPercent: 50
        ConnectionBorrowTimeout: 120  
   DependsOn: DBProxy