name: Python build test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.6'
    - name: Check Python version
      run: python --version
    - name: Install pipenv
      run: |
        pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install --dev --verbose
    - name: Run Unit Tests
      run: |
        pipenv run pytest --no-cov