name: Python build test pip cache
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.6'
    - name: Check Python version
      run: python --version
    - name: install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: ./.venv # since we know that .venv is gonna be created in the current working directory
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        pipenv install --dev --verbose
    - name: Unit tests
      run: |
        pipenv shell
        pipenv run pytest
